### PR TITLE
Add get-balance features to run test scenario

### PR DESCRIPTION
**Pull request by oteku**
## Problem

We want to easily run a test scenario where:
- one start a sandbox

```bash
docker compose up -d
./sandbox setup
```

**Note deku contract address**

- start deku
```bash
./sandbox start
```

- orignate a dummy ticket contract

dummy_ticket.mligo
```mligo
type storage = bytes ticket list

type return = operation list * storage

type vault_ticket = bytes ticket
type vault_deposit = {
  ticket: vault_ticket;
  address: address
}

type parameter =
| Deposit of {
  deku_consensus : address;
  deku_recipient : address;
  bytes : bytes;
}
| Withdraw of bytes ticket

let main (param, stored_tickets : parameter * storage) : return =
 match param with
 | Deposit {deku_consensus; deku_recipient; bytes} ->
   (match (Tezos.get_entrypoint_opt "%deposit" deku_consensus : vault_deposit contract option)  with 
   | Some contract ->
    (* Content of ticket is just a packed int *)
    let ticket = Tezos.create_ticket bytes 1000000n in 
    let param  = { ticket = ticket; address = deku_recipient } in
    let op = Tezos.transaction param 0mutez contract in
    (* We increment the counter to add some variety to the data *)
    [op], stored_tickets
   | None -> failwith "Entrypoint doesn't exist")
  | Withdraw ticket ->
    let ops : operation list = [] in
    ops , ticket :: stored_tickets
```

```bash
tezos-client --endpoint http://localhost:20000 originate contract "dummy_ticket" \
    transferring 0 from myWallet \
    running "$(ligo compile contract ./dummy_ticket.mligo)" \
    --init "{}" \
    --burn-cap 2 \
    --force
```
Note dummy contract address

- deposit a ticket from tezos to a deku address (node 0 address)

```bash
tezos-client --endpoint $RPC_NODE transfer 0 from myWallet to $DUMMY_CONTRACT \
  --entrypoint deposit --arg "Pair (Pair 0x10 \"$CONSENSUS_CONTRACT\") $(cat ./data/0/identity.json | jq .t)" \
  --burn-cap 2
```

- check that deposit works

```bash
esy x deku-cli get-balance ./data/0 $(cat ./data/0/identity.json | jq -r .t) "(Pair \"$DUMMY_CONTRACT\" 0x10)"
```
- do a transfert in deku (node 0 address -> node 1 address)

```bash
cat ./data/0/identity.json | jq '{ priv_key: .secret, address: .t }' > me.json && esy x deku-cli create-transaction ./data/0 me.json $(cat ./data/1/identity.json | jq -r .t) 42 "(Pair \"$DUMMY_CONTRACT\" 0x10)"
```

- check that transfert works

node 0 balance:
```bash
esy x deku-cli get-balance ./data/0 $(cat ./data/0/identity.json | jq -r .t) "(Pair \"$DUMMY_CONTRACT\" 0x10)"
```

node 1 balance:
```bash
esy x deku-cli get-balance ./data/0 $(cat ./data/1/identity.json | jq -r .t) "(Pair \"$DUMMY_CONTRACT\" 0x10)"
```

- withdraw a ticket in deku (7 tickets unit from node 0 to myWallet)

```bash
 esy x deku-cli withdraw ./data/0 me.json tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb 7 "(Pair \"$DUMMY_CONTRACT\" 0x10)"
 ```
**note operation hash**

- check node 0 balance

```bash
esy x deku-cli get-balance ./data/0 $(cat ./data/0/identity.json | jq -r .t) "(Pair \"$DUMMY_CONTRACT\" 0x10)"
```

- generate a withdraw_proof in deku

```bash
esy x deku-cli withdraw-proof ./data/0 "$WITHDRAW_HASH" "${DUMMY_CONTRACT}%withdraw"
```
Note the proof
_looks like_
```
(Pair (Pair "KT1TZiwWz63LLMZ2fC1gsQpocbFWUXjqjcwm%withdraw"
            (Pair (Pair 7 0x10) 0 "tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb")
            "KT1TZiwWz63LLMZ2fC1gsQpocbFWUXjqjcwm")
      0x7c4a56f9e72a0982543b9c9884b2491a75d0ff28f099aabe3e0247b76d89f0c1
      {  })
```

- withdraw in tezos with the withdraw proof

THINK TO ESCAPE CORRECTLY!!!
Looks like for the proof above

```bash
tezos-client --endpoint $RPC_NODE transfer 0 from myWallet to $CONSENSUS_CONTRACT \
  --entrypoint withdraw --arg "(Pair (Pair \"KT1TZiwWz63LLMZ2fC1gsQpocbFWUXjqjcwm%withdraw\" \
  (Pair (Pair 7 0x10) 0 \"tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb\") \
  \"KT1TZiwWz63LLMZ2fC1gsQpocbFWUXjqjcwm\") \
  0x7c4a56f9e72a0982543b9c9884b2491a75d0ff28f099aabe3e0247b76d89f0c1 \
  {  })" \
  --burn-cap 2
  ```

## Solution

- document the workflow
- add missing commands in deku-cli

## Related

- #570

### CODE REVIEW

**Review by AngryStitch — APPROVED** [review]
Thanks for adding it and the relevant man entry (that's amazing!)

**Review by InfiniteSwerve — APPROVED** [review]
Thanks for adding this, in a good format no less :+1:

**Review by gsebil08 — COMMENTED** [review]
This is great!
How about adding a doc/tutorial folder and add the one you have written in the conversation of this PR?

**Comment by aguillon** [comment]
> This is great! How about adding a doc/tutorial folder and add the one you have written in the conversation of this PR?

@gsebil08 I added an example call in sandbox for now, we can add Thomas' doc to the repo later when we start doing this sort of things.

**Pull request merged**
