### PR TITLE
Add error logging to taquito scripts

### PR DESCRIPTION
**Pull request by d4hines**
## Problem

I've found that any errors in Taquito aren't properly
logged, making it hard to debug them.

## Solution

Just add `console.error`.

### CODE REVIEW

**Review by gsebil08 — APPROVED** [review]
LGTM 👍

**Comment by EduardoRFS** [comment]
Why are they not properly logged? This is not addressing it and will duplicate a bunch of errors.

**Comment by d4hines** [comment]
As a compromise, I kept the `console.error` in NodeJS, but only send  a `{status: "error"}` obj to OCaml, omitting the error message. In  this way, the formatting and stack trace of the error message is preserved, but the information is only logged once instead of twice.

What do you think @EduardoRFS ?

**Comment by d4hines** [comment]
This PR is superceded by #497 and company

**Pull request closed without merging**
