### PR TITLE
fix: replace eprintf with logs

### PR DESCRIPTION
**Pull request by aguillon**
…except in tests

### CODE REVIEW

**Comment by ulrikstrid** [comment]
Some of these should maybe be `warn`?

**Comment by aguillon** [comment]
@ulrikstrid for gossip-related failures, you mean? I'm not sure I understand the subtleties of warning vs error.

**Comment by ulrikstrid** [comment]
As I see it a `error` is something that is not expected to happen so when it does we want to be notified (via alerts).
A `warning` is something that's not "good" but we don't expect anyone to act on it immediately.

@d4hines and @Laucans, do you have any other ideas here?

**Comment by d4hines** [comment]
@ulrikstrid @aguillon @Laucans I don't expect us to be able to figure out the best policy without trial and error tbh. I'll do a quick comb-through of these changes and see if any make more sense as alerts, then I'll merge. We can follow up with changes as needed.

**Pull request merged**
