### PR TITLE
chore: move start.sh into sandbox.sh as subcommand

### PR DESCRIPTION
**Pull request by d4hines**
## Problem

I want to add more stuff to our sandbox scripts. To prevent excessive duplication and potential mistakes,
I'd like to move ./start.sh into ./sandbox.sh, such that instead of running
```
./sandbox.sh setup
./start.sh
```
devs instead run
```
./sandbox.sh setup
./sandbox.sh start
```

## Solution

Move the code.

### CODE REVIEW

**Review by aguillon — APPROVED** [review]
Sure. Also makes it easier to tweak some parameters.

**Review by gsebil08 — APPROVED** [review]
LGTM, tried on my Debian, working like expected!

**Comment by d4hines** [comment]
@EduardoRFS, these changes look good to me. I'll update #491 accordingly.

**Review by EduardoRFS — APPROVED** [review]
anime girl happy at one less script

**Pull request merged**
