### PR TITLE
PROTO: Tz3 interop

### PR DESCRIPTION
**Pull request by Zett98**
## Depends

- [x] #318
## Problem

We don't have support for tz3 addresses in Crypto library right now, but we need it for tezos_interop
## Solution

This PR adds tz3 support to Crypto library

### CODE REVIEW

**Comment by Zett98** [comment]
> @Zett98 should this be reviewed?

No

**Comment by rosalogia** [comment]
Can I ask what has changed recently such that the PR is now ready for review? Was there ever a good answer to @d4hines question about what differentiates a Tz1 Addr. from a Tz3 Addr.?

**Comment by Zett98** [comment]
> Can I ask what has changed recently such that the PR is now ready for review? Was there ever a good answer to @d4hines question about what differentiates a Tz1 Addr. from a Tz3 Addr.?

1. Nothing really, I just moved the compression code to mirage-crypto repo and rebased this pr on top of the latest changes to main.(The pr there is still in process of review, but the tests from mirage-crypto pass, so i guess it will be added soon)
2. Tz1 uses Ed25519 curve while tz3 uses Nist P-256, also tz3 is mostly used by the tezos foundation.

**Comment by EduardoRFS** [comment]
@Zett98 is this ready to review?

**Comment by Zett98** [comment]
> @Zett98 is this ready to review?

yes

**Review by EduardoRFS — APPROVED** [review]
luffy smilling at a good PR

**Pull request merged**
