### PR TITLE
Annoying debug messages: upgrading piaf and dependencies

### PR DESCRIPTION
**Pull request by aguillon**
This PR is a draft because I need feedback regarding Nix.

## Problem

In his logging PR, @anchpop had to remove annoying debug messages from Piaf, and pin a specific commit of Piaf. His PR got accepted into Piaf so he removed the pin, but we didn't change the version we're using, and the debug messages are back.

Unfortunately, latest versions of Piaf use several dependencies that are not published, so the resulting esy file is a bit of a mess. Also I'm not sure about the state of affairs for Nix, can someone please take a look?

In the long run we should probably stop using Piaf.

(Sidenote: I should have tested logging one last time before merging and I'm sorry I didn't.)

## Solution

* Update Piaf
* Pin specific versions of `ocaml-sendfile` and `gluten` that are all required by Piaf

### CODE REVIEW

**Comment by ulrikstrid** [comment]
You can just do `nix flake update` and you should get the correct version

**Comment by aguillon** [comment]
@ulrikstrid after doing `nix flake update`, running `nix develop` gives me this:

```
error: 'init' at /nix/store/2s98acvj4g2ijm8wy6dq8la8cwh08nyi-source/src/lib.nix:63:10 called with unexpected argument 'systems'

       at /nix/store/yhmw3h3ha9syzax3q9nnf2v8177ky150-source/flake.nix:51:23:

           50|
           51|       dream2nix-lib = dream2nix.lib2.init {
             |                       ^
           52|         systems = supportedSystems;
(use '--show-trace' to show detailed location information)
```

🤷

**Comment by ulrikstrid** [comment]
```diff
diff --git a/flake.nix b/flake.nix
index 67eb6d69..51df8d00 100644
--- a/flake.nix
+++ b/flake.nix
@@ -47,19 +47,9 @@
     , prometheus-web, tezos, json-logs-reporter }:
     let
       supportedSystems = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ];
-
-      dream2nix-lib = dream2nix.lib2.init {
-        systems = supportedSystems;
-        config.projectRoot = ./.;
-      };
     in with flake-utils.lib;
     eachSystem supportedSystems (system:
       let
-        nodejs = pkgs.nodejs-16_x;
-
-        ligo = (import nixpkgs { inherit system; }).ligo.overrideAttrs
-          (_: { meta = { platforms = pkgs.ocaml.meta.platforms; }; });
-
         pkgs = (ocaml-overlays.makePkgs { inherit system; }).appendOverlays [
           (import ./nix/overlay.nix)
           prometheus-web.overlays.default
@@ -69,6 +59,15 @@
 
         pkgs_static = pkgs.pkgsCross.musl64;
 
+        dream2nix-lib = dream2nix.lib.init {
+          inherit pkgs;
+          config.projectRoot = ./.;
+        };
+        nodejs = pkgs.nodejs-16_x;
+
+        ligo = (import nixpkgs { inherit system; }).ligo.overrideAttrs
+          (_: { meta = { platforms = pkgs.ocaml.meta.platforms; }; });
+
         npmPackages = import ./nix/npm.nix {
           inherit system dream2nix-lib nix-filter nodejs;
         };
diff --git a/nix/npm.nix b/nix/npm.nix
index 2d9e89d0..2a430720 100644
--- a/nix/npm.nix
+++ b/nix/npm.nix
@@ -1,7 +1,7 @@
 { system, dream2nix-lib, nix-filter, nodejs }:
 
 let
-  outputs = (dream2nix-lib.makeFlakeOutputs {
+  outputs = (dream2nix-lib.makeOutputs {
     source = nix-filter.lib.filter {
       root = ../.;
       include = [ ../package-lock.json ../package.json ];
@@ -18,7 +18,7 @@ let
     settings =
       [{ subsystemInfo.nodejs = (builtins.substring 0 2 nodejs.version); }];
   });
-  npmPackages = outputs.packages."${system}".sidechain;
+  npmPackages = outputs.packages.sidechain;
 
   node_modules' = builtins.attrValues
     (builtins.removeAttrs npmPackages.dependencies [ "webpack" ]);
```

**Review by d4hines — APPROVED** [review]
Thanks for this guys.

**Pull request merged**
