### PR TITLE
WIP: add tutorial

### PR DESCRIPTION
**Pull request by d4hines**
## Problem

Configuring Deku is intrinsically complex.

## Solution

Help our users do it with a tutorial. The tutorial is a literate bash script, so it can be tested in CI.

This is a WIP: it's old and I haven't checked to see if it's still perfectly up to date. We also need to write the github action that tests it in CI. But it should be mostly accurate.

### CODE REVIEW

**Comment by aguillon** [comment]
Should we have both `tutorial/` and `notes/`? I'd move the former into the latter.

**Comment by lykimq** [comment]
> Should we have both `tutorial/` and `notes/`? I'd move the former into the latter.
I also prefer the second option: `notes/tutorial`

**Comment by lykimq** [comment]
> I don't like having a `./notes` dir committed. I'd prefer to have a `./docs` folder for official documentation. I don't know where notes should be written down, but I imagine it's in the source code as comments.

I agree to change notes to docs.

**Comment by d4hines** [comment]
> > I don't like having a `./notes` dir committed. I'd prefer to have a `./docs` folder for official documentation. I don't know where notes should be written down, but I imagine it's in the source code as comments.
> 
> I agree to change notes to docs. So maybe inside docs we can have notes?

`./docs` should be our public documentation.

**Pull request closed without merging**
